name: pytask

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.8
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - attrs >=21.3.0
  - click
  - click-default-group
  - networkx >=2.4
  - pluggy >=1.3.0
  - optree >=0.9
  - rich
  - sqlalchemy >=2
  - tomli >=1.0.0
  - typing_extensions
  - universal_pathlib >=0.2.2

  # Misc
  - deepdiff
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nbmake
  - pre-commit
  - pygraphviz
  - pytest
  - pytest-cov
  - pytest-xdist
  - ruff
  - syrupy
  - tabulate
  - tox-uv

  # Documentation
  - furo
  - myst-parser
  - nbsphinx
  - sphinx
  - sphinx-click
  - sphinx-copybutton
  - sphinx-design >=0.3.0
  - sphinxext-opengraph

  - pip:
    - sphinx-toolbox
    - -e .
