name: pytask
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - click
  - click-default-group
  - networkx
  - pluggy
  - pony
  - pytest

  # Misc
  - bump2version
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - pydot
  - pytest-cov
  - tox-conda

  # Documentation
  - nbsphinx
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - sphinx-autoapi
