name: pytask

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.7
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - attrs >=17.4.0
  - click
  - click-default-group
  - networkx
  - pluggy
  - pony >=0.7.15
  - pybaum
  - rich

  # Misc
  - black
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - pydot
  - pytest
  - pytest-cov
  - tox-conda

  # Documentation
  - furo
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - -e .
