name: pytask
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - click
  - networkx
  - pluggy
  - pony
  - pytest

  # Misc
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - pydot
  - pytest-cov

  # Documentation
  - nbsphinx
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-copybutton
